name: Update Monkeytype Stats
on:
  schedule:
    - cron: "0 */6 * * *" # Updates every 6 hours
  workflow_dispatch: # Allows you to run it manually

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Monkeytype SVG
        uses: ridemountainpig/monkeytype-readme@master
        with:
          monkeytype_username: DareOlolade
          api_key: ${{ secrets.MONKEYTYPE_API_KEY }}
